name: Deploy to production

on:
  push:
    branches: [ production ]

permissions:
  contents: read
  id-token: write
  deployments: write

    
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'angular-ui/package-lock.json'

      # Step 3: Install the project dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./angular-ui

      # Step 4: Build the Angular application for production
      - name: Build application
        run: npm run build -- --base-href /gepisopendata/ --configuration production
        working-directory: ./angular-ui

      # Step 4.1: Create 404.html from index.html for SPA routing
      - name: Create 404.html
        run: cp www/browser/index.html www/browser/404.html

      # Step 5: Prepare the deployment artifact
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 6: Upload the build artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This path should match the `outputPath` in your angular.json, which is ../www from the angular-ui dir
          path: './www/browser'

      # Step 7: Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
