name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - production

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    # These steps are executed as part of the job
    steps:
      # Step 1: Check out your repository code so the workflow can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js, which is needed to build your Angular app
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'angular-ui/package-lock.json'

      # Step 3: Install the project dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./angular-ui

      # Step 4: Build the Angular application for production
      - name: Build application
        run: npm run build -- --base-href /gepisopendata/ --configuration production
        working-directory: ./angular-ui

      # Step 4.1: Create 404.html from index.html for SPA routing
      - name: Create 404.html
        run: cp www/browser/index.html www/browser/404.html

      # Step 5: Prepare the deployment artifact
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 6: Upload the build artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This path should match the `outputPath` in your angular.json, which is ../www from the angular-ui dir
          path: './www/browser'

      # Step 7: Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
